WebLabs/Components/CartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebLabs.DAL.Data;
using WebLabs.Extensions;
using WebLabs.Models;

namespace WebLabs.Components
{
    public class CartViewComponent:ViewComponent
    {
        private Cart _cart;
        public CartViewComponent(Cart cart)
        {
            _cart = cart;

        }
        public IViewComponentResult Invoke()
        {
            // var cart = HttpContext.Session.Get<Cart>("cart") ?? new Cart();
            //return View(cart);

            return View(_cart);
        }

    }
}

WebLabs/Components/MenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebLabs.Models;

namespace WebLabs.Components
{
    public class MenuViewComponent:ViewComponent
    {
        // Инициализация списка элементов меню
        private List<MenuItem> _menuItems = new List<MenuItem>
        {
                new MenuItem{ Controller="Home", Action="Index", Text="Lab 2"},
                new MenuItem{ Controller="Product", Action="Index",Text="Каталог"},
                new MenuItem{ IsPage=true, Area="Admin", Page="/Index",Text="Администрирование"},
              //  new MenuItem{IsPage=true, Area="ApiDemo", Page="/Index", Text="API-demo"}
        };
        public IViewComponentResult Invoke()
        {
            //Получение значений сегментов маршрута
            var controller = ViewContext.RouteData.Values["controller"];
            var page = ViewContext.RouteData.Values["page"];
            var area = ViewContext.RouteData.Values["area"];
            foreach (var item in _menuItems)
            {
                // Название контроллера совпадает?
                var _matchController = controller?.Equals(item.Controller)
                ?? false;
                // Название зоны совпадает?
                var _matchArea = area?.Equals(item.Area) ?? false;
                // Если есть совпадение, то сделать элемент меню активным
                // (применить соответствующий класс CSS)
                if (_matchController || _matchArea)
                {
                    item.Active = "active";
                }
            }
            return View(_menuItems);
        }

    }
}

WebLabs/Views/Shared/_Layout - Копировать.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebLabs</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <div class="container">
            <!-- Панель навигации -->
            <nav class="navbar navbar-expand-md navbar-dark bg-dark">
                <!-- меню сайта -->
                <a class="navbar-brand" href="#">WebLabsAksenovDS</a>
                <div class="navbar-nav">
                    <a class="nav-item nav-link active"asp-controller="Home" asp-action="Index">Лб 1</a>
                    <a class="nav-item nav-link" href="#">Каталог</a>
                    <a class="nav-item nav-link"
                       href="#">Администрирование</a>
                </div>
                <!-- меню сайта - конец -->
                <!-- Информация пользователя -->
                <a href="#" class="navbar-text ml-auto">
                    <i class="fa fa-shopping-cart nav-color"></i> 0
                </a>
                <div class="dropdown ml-4 nav-color">
                    <div class="dropdown-toggle" id="dropdownMenuButton"
                         data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img src="images/avatar.jpg" width="30" alt="User"
                             class="rounded" />
                    </div>
                    <div class="dropdown-menu" arialabelledby="dropdownMenuButton">
                        <div class="dropdown-item-text">
                            <img src="images/avatar.jpg" width="50" alt="User"
                                 class="rounded" />
                            user@mail.ru
                        </div>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Мои товары</a>
                        <a class="dropdown-item" href="#">Log off</a>
                    </div>
                </div>
                <!-- Информация пользователя - конец -->
            </nav> <!-- Панель навигации - конец -->
        </div><!-- container - конец -->
    </header><!-- header - конец -->
    <main class="container">
@RenderBody()
    </main>
    <footer class="fixed-bottom">
        <div class="container">
            <div class="navbar navbar-dark navbar-expand-md bg-dark">
                <div class="navbar-nav ml-auto">
                    <a class="nav-item nav-link"
                       href="http://www.facebook.com">
                        <i class="fa fa-facebook fa-2x"></i>
                    </a>
                    <a class="nav-item nav-link" href="http://www.vk.com">
                        <i class="fa fa-vk fa-2x"></i>
                    </a>
                    <a class="nav-item nav-link" href="http://www.twitter.com">
                        <i class="fa fa-twitter fa-2x"></i>
                    </a>
                </div>
            </div>

        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WebLabs/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebLabs</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <div class="container">
            <!-- Панель навигации -->
            <nav class="navbar navbar-expand-md navbar-dark bg-dark">
                <!-- меню сайта -->
                <a class="navbar-brand" href="#">WebLabsAksenov</a>
                @await Component.InvokeAsync("Menu")
                <!-- меню сайта - конец -->
                <!-- Информация пользователя -->
                <partial name="_UserPartial" />
                <!-- Информация пользователя - конец -->
            </nav> <!-- Панель навигации - конец -->
        </div><!-- container - конец -->
    </header><!-- header - конец -->
    <main class="container">
        @RenderBody()
    </main>
    <footer class="fixed-bottom">
        <div class="container">
            <div class="navbar navbar-dark navbar-expand-md bg-dark">
                <div class="navbar-nav ml-auto">
                    <a class="nav-item nav-link"
                       href="http://www.facebook.com">
                        <i class="fa fa-facebook fa-2x"></i>
                    </a>
                    <a class="nav-item nav-link" href="http://www.vk.com">
                        <i class="fa fa-vk fa-2x"></i>
                    </a>
                    <a class="nav-item nav-link" href="http://www.twitter.com">
                        <i class="fa fa-twitter fa-2x"></i>
                    </a>
                </div>
            </div>

        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

</body>
</html>

WebLabs/Views/Shared/_UserPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@using Microsoft.AspNetCore.Identity;
@using WebLabs.DAL.Entities;
@inject SignInManager<ApplicationUser> signInManager
@if (signInManager.IsSignedIn(User))
{
    @await Component.InvokeAsync("Cart")
    <div class="dropdown ml-4 nav-color">
        <div class="dropdown-toggle" id="dropdownMenuButton"
             data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img img-action="GetAvatar"
                 img-controller="Image"
                 width="30" alt="User"
                 class="rounded bg-light" />
     </div>

        <div class="dropdown-menu" arialabelledby="dropdownMenuButton">
            <div class="dropdown-item-text">
                <img img-action="GetAvatar"
                     img-controller="Image"
                     width="50" alt="User"
                     class="rounded bg-light" />
                @User.Identity.Name
            </div>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" asp-controller="Product" asp-action="UserProducts">Мои товары</a>
            <form asp-area="Identity" asp-page="/Account/Logout" asp-route-returnurl="@ViewContext.HttpContext.Request.Path">
                <input type="submit" value="Log off" class="dropdown-item" />
            </form>
        </div>
    </div>
}
else
{
    <ul class="nav navbar-nav ml-auto">
        <li>
            <a class="nav-item nav-link"
               asp-area="Identity"
               asp-page="/Account/Login">
                Войти
            </a>
        </li>
        <li>
            <a class="nav-item nav-link"
               asp-area="Identity"
               asp-page="/Account/Register">
                Зарегистрироваться
            </a>
        </li>
    </ul>

}